[workspace]
members = [
	"common",
	"runtime",
	"runtime/tests/test_tvm_basic",
	"runtime/tests/test_nnvm",
	"frontend",
	"frontend/register_macro",
	"frontend/tests/basics",
	"frontend/tests/callback",
	"frontend/examples/resnet"
]
