[package]
name = "register_macro"
version = "0.1.0"
license = "Apache-2.0"
authors = ["TVM Contributors"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["full"] }
quote = "0.6"
